{% set name = "hdmedians" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b47aecb16771e1ba0736557255d80ae0240b09156bff434321de559b359ac2d6
  patches:
    - setup_reqs.patch

build:
  number: 2
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  build:
    - {{ compiler('c') }}
    - patch
  host:
    - cython
    - numpy {{ numpy }}
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
test:
  imports:
    - hdmedians
  requires:
    - pip
    - nose >=1.0
  source_files:
    - hdmedians/tests
  commands:
    - pip check
    - pip check
    - nosetests hdmedians/tests

about:
  home: https://github.com/daleroberts/hdmedians
  license: Apache-2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: High-dimensional medians
  description: |
    High-dimensional medians (medoid, geometric median, etc.). Fast implementations in Python.
  dev_url: https://github.com/daleroberts/hdmedians
  doc_url: https://github.com/daleroberts/hdmedians

extra:
  recipe-maintainers:
    - ElDeveloper
